### ISSUE TITLE
"This file has not been uploaded yet. This is likely due to do an error that occurred during release."

### ISSUE THREAD

**Issue by evansd** [opensafely-core/release-hatch#211]
Error displays for this file here:
https://jobs.opensafely.org/investigating-events-following-sars-cov-2-infection/post-covid-gastrointestina-extf/releases/01HD6KB2045GVD2R4BC1Z9PRQG/release/18_10_2023/table1_gi_bleeds_vax_rounded.csv

User reports that if they try to re-release they get an error saying file is already released.

Associated Slack thread:
https://bennettoxford.slack.com/archives/C01D7H9LYKB/p1697809942458629

**Comment by bloodearnest** [comment]
Not entirely sure what went wrong here, but we managed to release the file.
