### ISSUE TITLE
Release-related error

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/release-hatch#232]
A user reports that they released several outputs, but [the releases page][1] reports that an error occurred during release.[^1]

[1]: https://jobs.opensafely.org/investigating-events-following-sars-cov-2-infection/post-covid-gastrointestina-extf/releases/01HHFYYJ24EW80G9CW2NVWS824/

[^1]: https://bennettoxford.slack.com/archives/C0270Q313H7/p1702458006444519

**Comment by bloodearnest** [comment]
I manually fixed the state on L4 and release the files

**Comment by benbc** [comment]
@bloodearnest Do you know what the root cause was here? Is it a bug? (I'm categorizing tech support requests.)

**Comment by benbc** [comment]
Thanks, that's perfect.
