### ISSUE TITLE
Release attempt giving a 404 error 

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/release-hatch#248]
https://bennettoxford.slack.com/archives/C0270Q313H7/p1705490082101619

> When releasing files from L4, I get the error: `Error: 404 response from the server: {'detail': 'Not found.'}`. Specifically, I was trying to release files in the following folder: end-of-life-carequality/releases/20240116_Release. I was able to release files from a different workspace no problem.

**Comment by alschaffer** [comment]
I think this is sorted as I've managed to release the files - instead of requesting release of the entire folder, I specified the prefix for the two files within the folder (so, _releases/202401116_Release/cancer*.csv_).

**Comment by bloodearnest** [comment]
I think is probably because of a bug in osrelease, probably to do the directory issue. But given that its been worked around reasonablly, and the osrelease is about to be replaced, I'm inclined to close this.
