### ISSUE TITLE
Not all files in request released

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/release-hatch#286]
[This release request](https://jobs.opensafely.org/long-term-kidney-outcomes-after-sars-cov-2-infection/long_term_kidney_outcomes_after_covid/releases/01HY0DAJBR6QYM91X88VNAB11E/) shows 12 files.

However the bottom 5 (from descriptive_cabg_2017.csv onwards) have not been uploaded.  ("This file has not been uploaded yet. This is likely due to do an error that occurred during release.")

**Comment by bloodearnest** [comment]
Unsure how this happened, but job-server had the wrong hash stored for this file, so was refusing to let it be uploaded.

I uploaded the rest of the files, and added an additional release with the bad file.

https://jobs.opensafely.org/long-term-kidney-outcomes-after-sars-cov-2-infection/long_term_kidney_outcomes_after_covid/releases/01HYAW31S3P291QAZ53M6HT3Y7/

This is likely an odd interaction with job-server API and osrelease/release-hatch. Given they are on life support, am not planning to dig further
